language: node_js
node_js:
  - "6"
  - "node"
install:
  - npm install
script:
  - npm test
after_failure: 
  - "cat /home/travis/builds/dolanmiu/docx/npm-debug.log"
after_success:
  - git checkout gh-pages
  - git merge master --ff -m "merging with master"
  - npm run typedoc
  - git add .
  - git commit -a -m 'updated documentation'
  - git push
